# Generated by Django 4.1.6 on 2023-02-12 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tasks", models.CharField(help_text="Задание", max_length=250)),
                ("status", models.BooleanField(default=False)),
                (
                    "date_and_time_of_creation",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 12, 23, 57, 32, 337686),
                        help_text="Дата и время создания задания",
                    ),
                ),
                (
                    "date_and_time_of_completion",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Срок выполнения задания",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
